development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: ripple-switch-services_development

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: ripple-switch-services_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: ripple-switch-services_production
